spring:
  profiles:
    include: local
  application:
    name: bankingapp
  datasource:
    url: ${bankingapp.db.url}
    username: ${bankingapp.db.username}
    password: ${bankingapp.db.password}
  boot:
    admin:
      client:
        url: http://localhost:8081
        enabled: true
        auto-registeration: true
#server:
#  servlet:
#    context-path: /bankingapp
#logging:
#  level:
#    '[com.redmath.assignment.bankingapplication]': debug
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}] ${HOSTNAME}"
  file:
#    name: ${bankingapp.log.dir:target}/banking.log
    name: banking.log
    max-history: 20
    max-size: 20MB
  level:
    sql: debug
    '[org.springframework.web.servlet.DispatcherServlet]': debug
    '[org.springframework.web.client.RestTemplate]': debug
    '[com.redmath.assignment.bankingapplication]': debug


















#spring.security.user.name=admin
#spring.security.user.password=admin
#spring.security.user.role=test

##CORS Configuration
#spring.web.cors.allowed-origins=*
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.web.cors.allowed-headers=Authorization,Content-Type,Accept
#spring.web.cors.allow-credentials=true
#spring.web.cors.max-age=3600
#management.endpoints.web.exposure.include= *
#management.endpoint.health.show-details=always

# Set pool size
#spring:datasource.hikari.maximum-pool-size=10